//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alternativa
    {
        public Alternativa()
        {
            this.QuestaoGrupo = new HashSet<QuestaoGrupo>();
        }
    
        public int codQuestao { get; set; }
        public byte codAlternativa { get; set; }
        public string textoAlternativa { get; set; }
        public bool correta { get; set; }
    
        public virtual Questao Questao { get; set; }
        public virtual ICollection<QuestaoGrupo> QuestaoGrupo { get; set; }
    }
}
