//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Assunto = new HashSet<Assunto>();
        }
    
        public short codArea { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<Assunto> Assunto { get; set; }
    }
}
