//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assunto
    {
        public Assunto()
        {
            this.Grupo = new HashSet<Grupo>();
            this.Questao = new HashSet<Questao>();
            this.Evento = new HashSet<Evento>();
        }
    
        public int codAssunto { get; set; }
        public string descricao { get; set; }
        public short codArea { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual ICollection<Questao> Questao { get; set; }
        public virtual ICollection<Evento> Evento { get; set; }
    }
}
