//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.MasterEventos = new HashSet<MasterEventos>();
            this.Grupo = new HashSet<Grupo>();
            this.QuestaoEvento = new HashSet<QuestaoEvento>();
            this.Assunto = new HashSet<Assunto>();
        }
    
        public int codEvento { get; set; }
        public string descricao { get; set; }
        public System.DateTime data { get; set; }
        public byte codTipoEvento { get; set; }
        public string codStatus { get; set; }
        public short codProfessor { get; set; }
        public string identificador { get; set; }
    
        public virtual ICollection<MasterEventos> MasterEventos { get; set; }
        public virtual Status Status { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual ICollection<QuestaoEvento> QuestaoEvento { get; set; }
        public virtual ICollection<Assunto> Assunto { get; set; }
    }
}
