//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.MasterEventosOrdem = new HashSet<MasterEventosOrdem>();
            this.QuestaoGrupo = new HashSet<QuestaoGrupo>();
            this.Participante = new HashSet<Participante>();
        }
    
        public int codGrupo { get; set; }
        public int codEvento { get; set; }
        public string nmGrupo { get; set; }
        public Nullable<int> codAssunto { get; set; }
        public int codLider { get; set; }
        public Nullable<bool> finalizado { get; set; }
    
        public virtual Assunto Assunto { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual ICollection<MasterEventosOrdem> MasterEventosOrdem { get; set; }
        public virtual ICollection<QuestaoGrupo> QuestaoGrupo { get; set; }
        public virtual ICollection<Participante> Participante { get; set; }
    }
}
