//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterEventos
    {
        public int codToken { get; set; }
        public Nullable<short> codProfessor { get; set; }
        public string token { get; set; }
        public System.DateTime concedidoEm { get; set; }
        public System.DateTime expiraEm { get; set; }
        public Nullable<int> codEvento { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Professor Professor { get; set; }
    }
}
