//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Participante
    {
        public Participante()
        {
            this.Grupo = new HashSet<Grupo>();
        }
    
        public int codParticipante { get; set; }
        [DisplayName ("NOME ")]
        public string nmParticipante { get; set; }
        [DisplayName("CÓDIGO DO CURSO ")]
        public int codCurso { get; set; }
        [DisplayName("E-MAIL ")]
        public string email { get; set; }
        [DisplayName("SENHA ")]
        public byte[] senha { get; set; }
        [DisplayName("ATIVO ")]
        public bool ativo { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
    }
}
