//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public Professor()
        {
            this.Evento = new HashSet<Evento>();
            this.MasterEventos = new HashSet<MasterEventos>();
            this.Questao = new HashSet<Questao>();
        }
    
        public short codProfessor { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public byte[] senha { get; set; }
        public string idSenac { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<Evento> Evento { get; set; }
        public virtual ICollection<MasterEventos> MasterEventos { get; set; }
        public virtual ICollection<Questao> Questao { get; set; }
    }
}
