//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestaoEvento
    {
        public int codEvento { get; set; }
        public int codQuestao { get; set; }
        public string codStatus { get; set; }
        public Nullable<System.DateTime> tempo { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Questao Questao { get; set; }
        public virtual Status Status { get; set; }
    }
}
