//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questao
    {
        public Questao()
        {
            this.Alternativa = new HashSet<Alternativa>();
            this.QuestaoEvento = new HashSet<QuestaoEvento>();
        }
    
        public int codQuestao { get; set; }
        public string textoQuestao { get; set; }
        public int codAssunto { get; set; }
        public Nullable<int> codImagem { get; set; }
        public string codTipoQuestao { get; set; }
        public short codProfessor { get; set; }
        public bool ativo { get; set; }
        public string dificuldade { get; set; }
    
        public virtual ICollection<Alternativa> Alternativa { get; set; }
        public virtual Assunto Assunto { get; set; }
        public virtual Imagem Imagem { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual TipoQuestao TipoQuestao { get; set; }
        public virtual ICollection<QuestaoEvento> QuestaoEvento { get; set; }
    }
}
