//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestaoGrupo
    {
        public int codQuestao { get; set; }
        public byte codAlternativa { get; set; }
        public int codGrupo { get; set; }
        public Nullable<System.DateTime> tempo { get; set; }
        public string textoResp { get; set; }
        public bool correta { get; set; }
    
        public virtual Alternativa Alternativa { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
