//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidades : DbContext
    {
        public Entidades()
            : base("name=Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alternativa> Alternativa { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Assunto> Assunto { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Imagem> Imagem { get; set; }
        public virtual DbSet<MasterEventos> MasterEventos { get; set; }
        public virtual DbSet<Participante> Participante { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<Questao> Questao { get; set; }
        public virtual DbSet<QuestaoEvento> QuestaoEvento { get; set; }
        public virtual DbSet<QuestaoGrupo> QuestaoGrupo { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TipoEvento> TipoEvento { get; set; }
        public virtual DbSet<TipoQuestao> TipoQuestao { get; set; }
        public virtual DbSet<MasterEventosOrdem> MasterEventosOrdem { get; set; }

        internal void SaverChanges()
        {
            throw new NotImplementedException();
        }
    }
}
