//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Evento = new HashSet<Evento>();
            this.QuestaoEvento = new HashSet<QuestaoEvento>();
        }
    
        public string codStatus { get; set; }
        public string descStatus { get; set; }
    
        public virtual ICollection<Evento> Evento { get; set; }
        public virtual ICollection<QuestaoEvento> QuestaoEvento { get; set; }
    }
}
